### ISSUE TITLE
Biome Noise Reflection fails in production

### ISSUE THREAD

**Issue by Linguardium** [TerraformersMC/Cinderscapes#3]
In dev the reflection works fine, but in production i am getting
```
[20:32:44] [main/INFO]: [STDERR]: java.lang.NoSuchFieldException: noisePoints
[20:32:44] [main/INFO]: [STDERR]: 	at java.lang.Class.getDeclaredField(Unknown Source)
[20:32:44] [main/INFO]: [STDERR]: 	at com.terraformersmc.cinderscapes.util.NoiseCollisionChecker.check(NoiseCollisionChecker.java:35)
[20:32:44] [main/INFO]: [STDERR]: 	at com.terraformersmc.cinderscapes.util.NoiseCollisionChecker.init(NoiseCollisionChecker.java:21)
```
these errors.

**Comment by NeusFear** [comment]
Can you send the full log?

**Comment by Linguardium** [comment]
https://paste.ee/p/PcY17

**Comment by NeusFear** [comment]
Going to be honest, we have no idea why this uses reflection. We will work on a patch.

**Comment by Linguardium** [comment]
Looks like the fix using an accessor was committed already in b8699c5
going to close this as fixed.
