### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Zarpyk** [TerraformersMC/Cinderscapes#90]
Minecraft 1.16.3 
Cinderscapes 1.1.1

Crash when I died and go to nether (I use Origin and select Blazeborn and it make you spawn in nether)
I think it is this mod crash because in the log show this:
`at com.terraformersmc.cinderscapes.feature.CeilingShardFeature.generate(CeilingShardFeature.java:37) ~[cinderscapes-1.1.1+build.21-1.16.3.jar:?]
	at com.terraformersmc.cinderscapes.feature.CeilingShardFeature.method_13151(CeilingShardFeature.java:20) ~[cinderscapes-1.1.1+build.21-1.16.3.jar:?]
	`
https://gist.github.com/GuerreroCraft61/8fa4d98ae6342a0a5ece69e9f6eadd7e

**Comment by qixils** [comment]
Issue still occurs with FloorShardFeature in 1.1.2.
```
[16:00:27] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:872) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:303) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:808) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.NoSuchMethodError: net.minecraft.class_1158.<init>(FFFZ)V
        at com.terraformersmc.cinderscapes.feature.FloorShardFeature.generate(FloorShardFeature.java:36) ~[cinderscapes-1.1.2+build.24-1.16.3.jar:?]
        at com.terraformersmc.cinderscapes.feature.FloorShardFeature.method_13151(FloorShardFeature.java:20) ~[cinderscapes-1.1.2+build.24-1.16.3.jar:?]
```
